[package]
name = "relay-rialto-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
headers-relay = { path = "../headers-relay" }
relay-substrate-client = { path = "../substrate-client" }
relay-utils = { path = "../utils" }

# Bridge dependencies

rialto-runtime = { path = "../../bin/rialto/runtime" }

# Substrate Dependencies

frame-system = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
